import streamlit as st
import pandas as pd
import os
import requests
import plotly.graph_objects as go
import shutil
import json
import re
import sqlite3

try:
    import duckdb  # type: ignore
except Exception:
    duckdb = None

# ---------------------------------------------------
# Configuration
# ---------------------------------------------------

DATA_DIR = "/app/data"

BRONZE_PATH = os.path.join(DATA_DIR, "delta", "bronze")
SILVER_PATH = os.path.join(DATA_DIR, "delta", "silver")
GOLD_PATH = os.path.join(DATA_DIR, "delta", "gold")

INPUT_PATH = os.path.join(DATA_DIR, "input")

AIRFLOW_URL = os.getenv("AIRFLOW_URL", "http://airflow-webserver:8080")
AIRFLOW_DAG_ID = "event_driven_data_pipeline"

AIRFLOW_USERNAME = "admin"
AIRFLOW_PASSWORD = "admin"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")

# ---------------------------------------------------
# Streamlit Setup
# ---------------------------------------------------

st.set_page_config(
    page_title="Data Pipeline Dashboard",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------
# Custom CSS Styling
# ---------------------------------------------------

st.markdown("""
<style>

.metric-card{
padding:20px;
border-radius:12px;
color:white;
font-weight:bold;
text-align:center;
}

.bronze{background:#cd7f32;}
.silver{background:#9aa0a6;}
.gold{background:#f4c430;}

.upload-box{
border:2px dashed #bbb;
padding:30px;
border-radius:10px;
text-align:center;
background:#f8f9fa;
}

.stButton>button{
background:#2c7be5;
color:white;
border-radius:8px;
padding:10px 20px;
font-weight:bold;
}

.stButton>button:hover{
background:#1a5dcc;
}

</style>
""", unsafe_allow_html=True)

st.title("📊 Data Pipeline Monitoring Dashboard")

# ---------------------------------------------------
# Utility Functions
# ---------------------------------------------------

@st.cache_data(ttl=300)
def read_delta_table(path):

    try:

        parquet_files = []

        for root, dirs, files in os.walk(path):
            for file in files:
                if file.endswith(".parquet"):
                    parquet_files.append(os.path.join(root, file))

        if parquet_files:
            df = pd.concat([pd.read_parquet(f) for f in parquet_files])
            return df

        return pd.DataFrame()

    except Exception:
        return pd.DataFrame()


def get_table_info(path):

    if os.path.exists(path):

        df = read_delta_table(path)

        if not df.empty:
            return df

    return pd.DataFrame()


def get_layer_metrics(layer_name):
    """Reads the JSON metrics file generated by Spark jobs."""
    try:
        path = os.path.join(DATA_DIR, "delta", "metrics", f"{layer_name.lower()}_metrics.json")
        if os.path.exists(path):
            with open(path, "r") as f:
                return json.load(f)
    except Exception:
        return {}
    return {}


def get_available_tables():
    """Return non-empty layer DataFrames that can be queried."""
    tables = {}
    if not bronze_df.empty:
        tables["bronze"] = bronze_df.copy()
    if not silver_df.empty:
        tables["silver"] = silver_df.copy()
    if not gold_df.empty:
        tables["gold"] = gold_df.copy()
    return tables


def build_schema_context(tables):
    chunks = []
    for table_name, df in tables.items():
        schema = ", ".join([f"{c} ({str(df[c].dtype)})" for c in df.columns])
        sample = df.head(3).to_dict(orient="records")
        chunks.append(
            f"Table: {table_name}\n"
            f"Columns: {schema}\n"
            f"Sample rows: {json.dumps(sample, default=str)}\n"
        )
    return "\n".join(chunks)


def call_llm(messages, temperature=0.0):
    if not OPENAI_API_KEY:
        return None

    try:
        response = requests.post(
            f"{OPENAI_API_BASE}/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENAI_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": OPENAI_MODEL,
                "messages": messages,
                "temperature": temperature,
            },
            timeout=30,
        )
        if response.status_code != 200:
            return None
        data = response.json()
        return data["choices"][0]["message"]["content"].strip()
    except Exception:
        return None


def extract_sql(text):
    if not text:
        return None

    code_block = re.search(r"```sql\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if code_block:
        return code_block.group(1).strip()

    inline = re.search(r"(?is)select\s+.*", text)
    if inline:
        return inline.group(0).strip()

    return text.strip()


def nl_to_sql(question, tables):
    schema_context = build_schema_context(tables)
    table_list = ", ".join(tables.keys())

    sql_dialect = "DuckDB" if duckdb is not None else "SQLite"
    system_prompt = (
        "You are a data analyst SQL assistant. "
        f"Generate a single SELECT-only SQL query for {sql_dialect}. "
        "Use only the provided table names and columns. "
        "Never generate INSERT/UPDATE/DELETE/CREATE/DROP/ALTER."
    )
    user_prompt = (
        f"Available tables: {table_list}\n\n"
        f"{schema_context}\n"
        f"Question: {question}\n\n"
        "Return only SQL."
    )

    llm_output = call_llm(
        [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
    )

    if llm_output:
        sql = extract_sql(llm_output)
        if sql:
            return sql

    # Safe fallback when API key is absent/unavailable
    q = question.lower()
    if "count" in q and "gold" in q:
        return "SELECT COUNT(*) AS total_rows FROM gold;"
    if "count" in q and "silver" in q:
        return "SELECT COUNT(*) AS total_rows FROM silver;"
    if "count" in q and "bronze" in q:
        return "SELECT COUNT(*) AS total_rows FROM bronze;"
    if "top" in q:
        return "SELECT * FROM gold LIMIT 10;" if "gold" in tables else f"SELECT * FROM {list(tables.keys())[0]} LIMIT 10;"

    return f"SELECT * FROM {list(tables.keys())[0]} LIMIT 20;"


def is_safe_select(sql):
    if not sql:
        return False
    lowered = sql.strip().lower().rstrip(";")
    blocked = ["insert ", "update ", "delete ", "drop ", "alter ", "create ", "truncate "]
    return lowered.startswith("select") and not any(token in lowered for token in blocked)


def run_sql_on_layers(sql, tables):
    if duckdb is not None:
        conn = duckdb.connect(database=":memory:")
        try:
            for name, df in tables.items():
                conn.register(name, df)
            return conn.execute(sql).df()
        finally:
            conn.close()

    conn = sqlite3.connect(":memory:")
    try:
        for name, df in tables.items():
            df.to_sql(name, conn, index=False, if_exists="replace")
        return pd.read_sql_query(sql, conn)
    finally:
        conn.close()


def humanize_answer(question, sql, result_df):
    if result_df.empty:
        return "I could not find matching records for that question in the available data."

    preview = result_df.head(10).to_dict(orient="records")
    llm_output = call_llm(
        [
            {
                "role": "system",
                "content": "You explain SQL query outputs to non-technical users in concise plain English.",
            },
            {
                "role": "user",
                "content": (
                    f"Question: {question}\n"
                    f"SQL: {sql}\n"
                    f"Rows returned: {len(result_df)}\n"
                    f"Preview: {json.dumps(preview, default=str)}\n"
                    "Give a short human-readable answer."
                ),
            },
        ],
        temperature=0.2,
    )

    if llm_output:
        return llm_output

    first_row = result_df.iloc[0].to_dict()
    return (
        f"I ran your question as SQL and found {len(result_df)} result row(s). "
        f"The first row is: {first_row}"
    )


# ---------------------------------------------------
# Trigger Airflow DAG
# ---------------------------------------------------

def trigger_airflow(file_name: str):

    try:

        response = requests.post(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            json={"conf": {"file_name": file_name}},
            timeout=10
        )

        if response.status_code in [200, 201]:

            return True

        else:

            st.error(f"Airflow API error {response.status_code}")
            st.code(response.text)
            return False

    except Exception as e:

        st.error(f"Airflow trigger failed: {str(e)}")
        return False


def stop_pipeline(run_id):
    """Stops a running pipeline by marking it as failed."""
    try:
        response = requests.patch(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns/{run_id}",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            json={"state": "failed"},
            timeout=10
        )

        if response.status_code == 200:
            return True
        else:
            st.error(f"Failed to stop pipeline: {response.text}")
            return False

    except Exception as e:
        st.error(f"Error stopping pipeline: {str(e)}")
        return False


# ---------------------------------------------------
# Get Pipeline Runs
# ---------------------------------------------------

def get_dag_runs():

    try:

        response = requests.get(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns?limit=5",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            timeout=10
        )

        if response.status_code == 200:

            return response.json().get("dag_runs", [])

        else:

            st.error(f"Airflow API error {response.status_code}")
            return []

    except Exception:

        st.error("Unable to fetch pipeline status")
        return []


# ---------------------------------------------------
# Sidebar Navigation
# ---------------------------------------------------

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Go To",
    ["Overview", "Data Layers", "Upload Data", "Pipeline Status", "AI Analyst"]
)

st.sidebar.markdown("---")
st.sidebar.markdown("### ⚙️ System Controls")

if st.sidebar.button("🗑️ Reset All Data"):
    try:
        # Delete Delta directories (subfolders) completely
        for path in [BRONZE_PATH, SILVER_PATH, GOLD_PATH, os.path.join(DATA_DIR, "delta", "metrics")]:
            if os.path.exists(path):
                shutil.rmtree(path)

        # Delete CONTENTS of Input directory (Mount point cannot be removed)
        if os.path.exists(INPUT_PATH):
            for item in os.listdir(INPUT_PATH):
                item_path = os.path.join(INPUT_PATH, item)
                if os.path.isfile(item_path):
                    os.unlink(item_path)

        st.cache_data.clear()
        st.success("System data wiped successfully!")
        st.rerun()
    except Exception as e:
        st.error(f"Error resetting data: {e}")

# ---------------------------------------------------
# Load Data Layers
# ---------------------------------------------------

bronze_df = get_table_info(BRONZE_PATH)
silver_df = get_table_info(SILVER_PATH)
gold_df = get_table_info(GOLD_PATH)

# ---------------------------------------------------
# Overview Page
# ---------------------------------------------------

if page == "Overview":

    st.subheader("Pipeline Overview")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown(
            f"""
            <div class="metric-card bronze">
            Bronze Layer<br>
            {len(bronze_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    with col2:
        st.markdown(
            f"""
            <div class="metric-card silver">
            Silver Layer<br>
            {len(silver_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    with col3:
        st.markdown(
            f"""
            <div class="metric-card gold">
            Gold Layer<br>
            {len(gold_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("### Pipeline Flow")

    layers = ["Bronze", "Silver", "Gold"]
    counts = [len(bronze_df), len(silver_df), len(gold_df)]

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=layers,
        y=counts,
        mode="lines+markers",
        line=dict(width=4),
        marker=dict(size=12)
    ))

    fig.update_layout(height=350)

    st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------
# Data Layer Explorer
# ---------------------------------------------------

elif page == "Data Layers":

    st.subheader("Explore Data Layers")

    layer = st.selectbox(
        "Select Layer",
        ["Bronze", "Silver", "Gold"]
    )

    if layer == "Bronze":
        df = bronze_df
    elif layer == "Silver":
        df = silver_df
    else:
        df = gold_df

    if df.empty:

        st.warning("No data available in this layer")

    else:

        # Display custom metrics from Spark jobs
        metrics = get_layer_metrics(layer)
        
        if metrics:
            cols = st.columns(len(metrics))
            for idx, (key, value) in enumerate(metrics.items()):
                with cols[idx]:
                    st.metric(label=key.replace("_", " ").title(), value=value)
        else:
            st.metric("Total Records", len(df))

        st.dataframe(df, use_container_width=True)

# ---------------------------------------------------
# Upload CSV Files
# ---------------------------------------------------

elif page == "Upload Data":

    st.subheader("Upload CSV Files")

    st.markdown(
        '<div class="upload-box">Upload one or more CSV files to start the pipeline</div>',
        unsafe_allow_html=True
    )

    uploaded_files = st.file_uploader(
        "Choose CSV files",
        type="csv",
        accept_multiple_files=True
    )

    if uploaded_files:

        valid_files = [f for f in uploaded_files if f.name.lower().endswith('.csv')]
        invalid_files = [f for f in uploaded_files if not f.name.lower().endswith('.csv')]

        # Show a prominent error for any invalid files. This acts like a "pop-up" warning.
        if invalid_files:
            st.error(f"❌ Invalid File Type: The following files were rejected as only CSV is allowed: {', '.join([f.name for f in invalid_files])}")

        # Only proceed if there are valid files to process.
        if valid_files:
            st.success(f"✅ {len(valid_files)} CSV file(s) are valid and ready to upload.")

            # Check for running pipelines to avoid conflicts
            running_runs = [r for r in get_dag_runs() if r['state'] == 'running']

            if running_runs:
                st.warning(f"⚠️ A pipeline is already running ({running_runs[0]['dag_run_id']}). Please wait for it to finish.")
            elif st.button("🚀 Upload & Start Pipeline"):

                os.makedirs(INPUT_PATH, exist_ok=True)

                # Only save the valid files
                for file in valid_files:
                    path = os.path.join(INPUT_PATH, file.name)
                    with open(path, "wb") as f:
                        f.write(file.getbuffer())

                st.success("Valid CSV files uploaded successfully.")

                # We'll trigger the pipeline for the first valid uploaded file.
                file_to_process = valid_files[0].name
                st.info(f"Triggering pipeline for: {file_to_process}...")

                if trigger_airflow(file_to_process):

                    st.success("Pipeline started successfully")
                    st.balloons()
                    st.link_button(
                        "Open Airflow Dashboard",
                        "http://localhost:8081"
                    )

                else:
                    st.error("Failed to trigger DAG")

# ---------------------------------------------------
# Pipeline Status
# ---------------------------------------------------

elif page == "Pipeline Status":

    st.subheader("Recent Pipeline Runs")

    runs = get_dag_runs()

    if not runs:

        st.info("No pipeline runs yet")

    else:

        for run in runs:

            with st.expander(f"{run['dag_run_id']} — {run['state']}"):

                st.write("Start:", run["start_date"])
                st.write("End:", run["end_date"])

                # Allow stopping stuck runs
                if run["state"] == "running":
                    if st.button("⛔ Stop Run", key=f"stop_{run['dag_run_id']}"):
                        if stop_pipeline(run["dag_run_id"]):
                            st.success(f"Run {run['dag_run_id']} stopped!")
                            st.rerun()

# ---------------------------------------------------
# AI Analyst
# ---------------------------------------------------

elif page == "AI Analyst":

    st.subheader("Ask Data In Plain English")
    st.caption("The agent converts your question to SQL over Bronze/Silver/Gold and explains the result.")

    available_tables = get_available_tables()
    if not available_tables:
        st.warning("No data found in Bronze/Silver/Gold yet. Run the pipeline first.")
    else:
        st.write("Queryable tables:", ", ".join(available_tables.keys()))

        if not OPENAI_API_KEY:
            st.info(
                "OPENAI_API_KEY is not set. SQL generation will use fallback rules. "
                "Set OPENAI_API_KEY in docker-compose for full natural-language understanding."
            )

        if duckdb is None:
            st.warning(
                "duckdb is not available in this container. Running AI SQL with SQLite fallback. "
                "You can still query data, but some advanced SQL syntax may differ."
            )

        user_question = st.text_area(
            "Ask your question",
            placeholder="Example: What are the top 5 locations by total_spent in gold layer?",
            height=120,
        )

        if st.button("Run AI Query", type="primary"):
            if not user_question.strip():
                st.warning("Please enter a question first.")
            else:
                try:
                    sql = nl_to_sql(user_question, available_tables)
                    st.markdown("### Generated SQL")
                    st.code(sql, language="sql")

                    if not is_safe_select(sql):
                        st.error("Generated query was blocked because it is not a safe SELECT statement.")
                    else:
                        result = run_sql_on_layers(sql, available_tables)
                        st.markdown("### Result")
                        st.dataframe(result, use_container_width=True)

                        answer = humanize_answer(user_question, sql, result)
                        st.markdown("### Human-Readable Answer")
                        st.write(answer)

                except Exception as e:
                    st.error(f"AI query failed: {e}")

# ---------------------------------------------------
# Footer
# ---------------------------------------------------

st.markdown("---")
st.caption("Built with Streamlit • Spark • Delta Lake • Airflow")