import streamlit as st
import pandas as pd
import os
import requests
import plotly.graph_objects as go
import shutil
import json

# ---------------------------------------------------
# Configuration
# ---------------------------------------------------

DATA_DIR = "/app/data"

BRONZE_PATH = os.path.join(DATA_DIR, "delta", "bronze")
SILVER_PATH = os.path.join(DATA_DIR, "delta", "silver")
GOLD_PATH = os.path.join(DATA_DIR, "delta", "gold")

INPUT_PATH = os.path.join(DATA_DIR, "input")

AIRFLOW_URL = os.getenv("AIRFLOW_URL", "http://airflow-webserver:8080")
AIRFLOW_DAG_ID = "event_driven_data_pipeline"

AIRFLOW_USERNAME = "admin"
AIRFLOW_PASSWORD = "admin"

# ---------------------------------------------------
# Streamlit Setup
# ---------------------------------------------------

st.set_page_config(
    page_title="Data Pipeline Dashboard",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------
# Custom CSS Styling
# ---------------------------------------------------

st.markdown("""
<style>

.metric-card{
padding:20px;
border-radius:12px;
color:white;
font-weight:bold;
text-align:center;
}

.bronze{background:#cd7f32;}
.silver{background:#9aa0a6;}
.gold{background:#f4c430;}

.upload-box{
border:2px dashed #bbb;
padding:30px;
border-radius:10px;
text-align:center;
background:#f8f9fa;
}

.stButton>button{
background:#2c7be5;
color:white;
border-radius:8px;
padding:10px 20px;
font-weight:bold;
}

.stButton>button:hover{
background:#1a5dcc;
}

</style>
""", unsafe_allow_html=True)

st.title("📊 Data Pipeline Monitoring Dashboard")

# ---------------------------------------------------
# Utility Functions
# ---------------------------------------------------

@st.cache_data(ttl=300)
def read_delta_table(path):

    try:

        parquet_files = []

        for root, dirs, files in os.walk(path):
            for file in files:
                if file.endswith(".parquet"):
                    parquet_files.append(os.path.join(root, file))

        if parquet_files:
            df = pd.concat([pd.read_parquet(f) for f in parquet_files])
            return df

        return pd.DataFrame()

    except Exception:
        return pd.DataFrame()


def get_table_info(path):

    if os.path.exists(path):

        df = read_delta_table(path)

        if not df.empty:
            return df

    return pd.DataFrame()


def get_layer_metrics(layer_name):
    """Reads the JSON metrics file generated by Spark jobs."""
    try:
        path = os.path.join(DATA_DIR, "delta", "metrics", f"{layer_name.lower()}_metrics.json")
        if os.path.exists(path):
            with open(path, "r") as f:
                return json.load(f)
    except Exception:
        return {}
    return {}


# ---------------------------------------------------
# Trigger Airflow DAG
# ---------------------------------------------------

def trigger_airflow(file_name: str):

    try:

        response = requests.post(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            json={"conf": {"file_name": file_name}},
            timeout=10
        )

        if response.status_code in [200, 201]:

            return True

        else:

            st.error(f"Airflow API error {response.status_code}")
            st.code(response.text)
            return False

    except Exception as e:

        st.error(f"Airflow trigger failed: {str(e)}")
        return False


def stop_pipeline(run_id):
    """Stops a running pipeline by marking it as failed."""
    try:
        response = requests.patch(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns/{run_id}",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            json={"state": "failed"},
            timeout=10
        )

        if response.status_code == 200:
            return True
        else:
            st.error(f"Failed to stop pipeline: {response.text}")
            return False

    except Exception as e:
        st.error(f"Error stopping pipeline: {str(e)}")
        return False


# ---------------------------------------------------
# Get Pipeline Runs
# ---------------------------------------------------

def get_dag_runs():

    try:

        response = requests.get(
            f"{AIRFLOW_URL}/api/v1/dags/{AIRFLOW_DAG_ID}/dagRuns?limit=5",
            auth=(AIRFLOW_USERNAME, AIRFLOW_PASSWORD),
            headers={"Content-Type": "application/json"},
            timeout=10
        )

        if response.status_code == 200:

            return response.json().get("dag_runs", [])

        else:

            st.error(f"Airflow API error {response.status_code}")
            return []

    except Exception:

        st.error("Unable to fetch pipeline status")
        return []


# ---------------------------------------------------
# Sidebar Navigation
# ---------------------------------------------------

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Go To",
    ["Overview", "Data Layers", "Upload Data", "Pipeline Status"]
)

st.sidebar.markdown("---")
st.sidebar.markdown("### ⚙️ System Controls")

if st.sidebar.button("🗑️ Reset All Data"):
    try:
        # Delete Delta directories (subfolders) completely
        for path in [BRONZE_PATH, SILVER_PATH, GOLD_PATH, os.path.join(DATA_DIR, "delta", "metrics")]:
            if os.path.exists(path):
                shutil.rmtree(path)

        # Delete CONTENTS of Input directory (Mount point cannot be removed)
        if os.path.exists(INPUT_PATH):
            for item in os.listdir(INPUT_PATH):
                item_path = os.path.join(INPUT_PATH, item)
                if os.path.isfile(item_path):
                    os.unlink(item_path)

        st.cache_data.clear()
        st.success("System data wiped successfully!")
        st.rerun()
    except Exception as e:
        st.error(f"Error resetting data: {e}")

# ---------------------------------------------------
# Load Data Layers
# ---------------------------------------------------

bronze_df = get_table_info(BRONZE_PATH)
silver_df = get_table_info(SILVER_PATH)
gold_df = get_table_info(GOLD_PATH)

# ---------------------------------------------------
# Overview Page
# ---------------------------------------------------

if page == "Overview":

    st.subheader("Pipeline Overview")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown(
            f"""
            <div class="metric-card bronze">
            Bronze Layer<br>
            {len(bronze_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    with col2:
        st.markdown(
            f"""
            <div class="metric-card silver">
            Silver Layer<br>
            {len(silver_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    with col3:
        st.markdown(
            f"""
            <div class="metric-card gold">
            Gold Layer<br>
            {len(gold_df)} records
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("### Pipeline Flow")

    layers = ["Bronze", "Silver", "Gold"]
    counts = [len(bronze_df), len(silver_df), len(gold_df)]

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=layers,
        y=counts,
        mode="lines+markers",
        line=dict(width=4),
        marker=dict(size=12)
    ))

    fig.update_layout(height=350)

    st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------
# Data Layer Explorer
# ---------------------------------------------------

elif page == "Data Layers":

    st.subheader("Explore Data Layers")

    layer = st.selectbox(
        "Select Layer",
        ["Bronze", "Silver", "Gold"]
    )

    if layer == "Bronze":
        df = bronze_df
    elif layer == "Silver":
        df = silver_df
    else:
        df = gold_df

    if df.empty:

        st.warning("No data available in this layer")

    else:

        # Display custom metrics from Spark jobs
        metrics = get_layer_metrics(layer)
        
        if metrics:
            cols = st.columns(len(metrics))
            for idx, (key, value) in enumerate(metrics.items()):
                with cols[idx]:
                    st.metric(label=key.replace("_", " ").title(), value=value)
        else:
            st.metric("Total Records", len(df))

        st.dataframe(df, use_container_width=True)

# ---------------------------------------------------
# Upload CSV Files
# ---------------------------------------------------

elif page == "Upload Data":

    st.subheader("Upload CSV Files")

    st.markdown(
        '<div class="upload-box">Upload one or more CSV files to start the pipeline</div>',
        unsafe_allow_html=True
    )

    uploaded_files = st.file_uploader(
        "Choose CSV files",
        type="csv",
        accept_multiple_files=True
    )

    if uploaded_files:

        valid_files = [f for f in uploaded_files if f.name.lower().endswith('.csv')]
        invalid_files = [f for f in uploaded_files if not f.name.lower().endswith('.csv')]

        # Show a prominent error for any invalid files. This acts like a "pop-up" warning.
        if invalid_files:
            st.error(f"❌ Invalid File Type: The following files were rejected as only CSV is allowed: {', '.join([f.name for f in invalid_files])}")

        # Only proceed if there are valid files to process.
        if valid_files:
            st.success(f"✅ {len(valid_files)} CSV file(s) are valid and ready to upload.")

            # Check for running pipelines to avoid conflicts
            running_runs = [r for r in get_dag_runs() if r['state'] == 'running']

            if running_runs:
                st.warning(f"⚠️ A pipeline is already running ({running_runs[0]['dag_run_id']}). Please wait for it to finish.")
            elif st.button("🚀 Upload & Start Pipeline"):

                os.makedirs(INPUT_PATH, exist_ok=True)

                # Only save the valid files
                for file in valid_files:
                    path = os.path.join(INPUT_PATH, file.name)
                    with open(path, "wb") as f:
                        f.write(file.getbuffer())

                st.success("Valid CSV files uploaded successfully.")

                # We'll trigger the pipeline for the first valid uploaded file.
                file_to_process = valid_files[0].name
                st.info(f"Triggering pipeline for: {file_to_process}...")

                if trigger_airflow(file_to_process):

                    st.success("Pipeline started successfully")
                    st.balloons()
                    st.link_button(
                        "Open Airflow Dashboard",
                        "http://localhost:8081"
                    )

                else:
                    st.error("Failed to trigger DAG")

# ---------------------------------------------------
# Pipeline Status
# ---------------------------------------------------

elif page == "Pipeline Status":

    st.subheader("Recent Pipeline Runs")

    runs = get_dag_runs()

    if not runs:

        st.info("No pipeline runs yet")

    else:

        for run in runs:

            with st.expander(f"{run['dag_run_id']} — {run['state']}"):

                st.write("Start:", run["start_date"])
                st.write("End:", run["end_date"])

                # Allow stopping stuck runs
                if run["state"] == "running":
                    if st.button("⛔ Stop Run", key=f"stop_{run['dag_run_id']}"):
                        if stop_pipeline(run["dag_run_id"]):
                            st.success(f"Run {run['dag_run_id']} stopped!")
                            st.rerun()

# ---------------------------------------------------
# Footer
# ---------------------------------------------------

st.markdown("---")
st.caption("Built with Streamlit • Spark • Delta Lake • Airflow")